version: '3.6'

services:
  auldfellas:
    build:
      context: ./auldfellas
    networks:
      - mynet
    container_name: auldfellas
    depends_on:
      - broker

  broker:
    build:
      context: ./broker
    networks:
      - mynet
    ports:
      - "8083:8083"
    container_name: broker

  dodgygeezers:
    build:
      context: ./dodgygeezers
    networks:
      - mynet
    container_name: dodgygeezers
    depends_on:
      - broker

  girlsallowed:
    build:
      context: ./girlsallowed
    networks:
      - mynet
    container_name: girlsallowed
    depends_on:
      - broker

networks:
  mynet:
    driver: bridge






